### PR TITLE
Fix docker run command so it works on mac os

### PR DESCRIPTION
**Pull request by alakahakai**
Address issue #68, so the build script will work on mac os with docker desktop.

### CODE REVIEW

**Comment by jarpy** [comment]
Since the master branch of this repo is obsolete, where would you like this backported?

**Comment by alakahakai** [comment]
Will there be no 7.0.0 release for this repo?

**Comment by jarpy** [comment]
That's correct. We are moving all the Docker image builds into the main source repositories of the products themselves.

You can find the new-generation Beats image build over [here](https://github.com/elastic/beats/tree/master/dev-tools/packaging/templates/docker).

**Comment by kvch** [comment]
Closing this PR, as the repo is going to be archived. Please open your PR in https://github.com/elastic/beats

**Pull request closed without merging**
